/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Footwise.view;
import javax.swing.*;

/*
 * LMU ID: 23048665
 * Name: Devanshi Baishya
 */
public class About_Uspage extends javax.swing.JFrame {

    /**
     * Creates new form About_Uspage
     */
    public About_Uspage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Aboutusmainpanel = new javax.swing.JPanel();
        Logolabelcontactpage = new javax.swing.JLabel();
        aboutUsSlogan = new javax.swing.JLabel();
        titleaboutuspage = new javax.swing.JLabel();
        Homeaboutuspage = new javax.swing.JButton();
        Informationaboutuspage = new javax.swing.JButton();
        Contactuspageaboutus = new javax.swing.JButton();
        aboutustitle = new javax.swing.JLabel();
        questionlabel = new javax.swing.JLabel();
        Answerlabel = new javax.swing.JLabel();
        Missionlabel = new javax.swing.JLabel();
        ScrollpaneMission = new javax.swing.JScrollPane();
        MissionTextArea = new javax.swing.JTextArea();
        Aboutfigurelabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Aboutusmainpanel.setBackground(new java.awt.Color(51, 51, 0));

        Logolabelcontactpage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Footwise/resources/esmalllogo.png"))); // NOI18N

        aboutUsSlogan.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        aboutUsSlogan.setForeground(new java.awt.Color(255, 255, 255));
        aboutUsSlogan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutUsSlogan.setText("Remember ... You Deserve the Best Or Nothing");

        titleaboutuspage.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        titleaboutuspage.setForeground(new java.awt.Color(255, 255, 255));
        titleaboutuspage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleaboutuspage.setText("Foot~Wise");

        Homeaboutuspage.setText("Home");
        Homeaboutuspage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeaboutuspageActionPerformed(evt);
            }
        });

        Informationaboutuspage.setText("Information");

        Contactuspageaboutus.setText("Contact Us");
        Contactuspageaboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactuspageaboutusActionPerformed(evt);
            }
        });

        aboutustitle.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        aboutustitle.setForeground(new java.awt.Color(255, 255, 255));
        aboutustitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutustitle.setText("About Us");

        questionlabel.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        questionlabel.setForeground(new java.awt.Color(255, 204, 204));
        questionlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionlabel.setText("Que. Why to choose us ? ");

        Answerlabel.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        Answerlabel.setForeground(new java.awt.Color(255, 255, 255));
        Answerlabel.setText(" Ans:   Innovation, Affordability, Sustainability");
        Answerlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 2));

        Missionlabel.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        Missionlabel.setForeground(new java.awt.Color(255, 255, 255));
        Missionlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Missionlabel.setText("Mission");

        MissionTextArea.setBackground(new java.awt.Color(51, 51, 0));
        MissionTextArea.setColumns(20);
        MissionTextArea.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        MissionTextArea.setForeground(new java.awt.Color(255, 255, 255));
        MissionTextArea.setRows(5);
        MissionTextArea.setText("  At Foot~Wise, we empower individuals to express their unique style and \n  confidence through high-quality, comfortable footwear. Committed to\n  sustainability and innovation, we craft shoes that elevate your look  \n  while respecting our planet, inspiring every step of your journey with  \n  purpose and pride.");
        MissionTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 2));
        ScrollpaneMission.setViewportView(MissionTextArea);

        Aboutfigurelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Aboutfigurelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Footwise/resources/Aboutuspage.jpg"))); // NOI18N

        javax.swing.GroupLayout AboutusmainpanelLayout = new javax.swing.GroupLayout(Aboutusmainpanel);
        Aboutusmainpanel.setLayout(AboutusmainpanelLayout);
        AboutusmainpanelLayout.setHorizontalGroup(
            AboutusmainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutusmainpanelLayout.createSequentialGroup()
                .addComponent(Logolabelcontactpage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AboutusmainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AboutusmainpanelLayout.createSequentialGroup()
                        .addComponent(Homeaboutuspage)
                        .addGap(18, 18, 18)
                        .addComponent(Informationaboutuspage)
                        .addGap(18, 18, 18)
                        .addComponent(Contactuspageaboutus)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(titleaboutuspage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aboutUsSlogan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(AboutusmainpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aboutustitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AboutusmainpanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(AboutusmainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(questionlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Answerlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addComponent(Aboutfigurelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 203, Short.MAX_VALUE)
                .addGroup(AboutusmainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Missionlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ScrollpaneMission, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE))
                .addContainerGap())
        );
        AboutusmainpanelLayout.setVerticalGroup(
            AboutusmainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutusmainpanelLayout.createSequentialGroup()
                .addGroup(AboutusmainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AboutusmainpanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(aboutUsSlogan, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutusmainpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AboutusmainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Logolabelcontactpage)
                            .addComponent(titleaboutuspage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AboutusmainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Homeaboutuspage)
                    .addComponent(Informationaboutuspage)
                    .addComponent(Contactuspageaboutus))
                .addGap(18, 18, 18)
                .addComponent(aboutustitle, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AboutusmainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(questionlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Missionlabel))
                .addGroup(AboutusmainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AboutusmainpanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Answerlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(Aboutfigurelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutusmainpanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(ScrollpaneMission, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Aboutusmainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Aboutusmainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContactuspageaboutusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactuspageaboutusActionPerformed
          new Contactuspage().setVisible(true);
    }//GEN-LAST:event_ContactuspageaboutusActionPerformed

    private void HomeaboutuspageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeaboutuspageActionPerformed
      new Homepage().setVisible(true);
    }//GEN-LAST:event_HomeaboutuspageActionPerformed

    private void InformationpageActionPerformed(java.awt.event.ActionEvent evt) {                                                
      new Informationpage().setVisible(true);
    }      

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About_Uspage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About_Uspage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About_Uspage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About_Uspage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About_Uspage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aboutfigurelabel;
    private javax.swing.JPanel Aboutusmainpanel;
    private javax.swing.JLabel Answerlabel;
    private javax.swing.JButton Contactuspageaboutus;
    private javax.swing.JButton Homeaboutuspage;
    private javax.swing.JButton Informationaboutuspage;
    private javax.swing.JLabel Logolabelcontactpage;
    private javax.swing.JTextArea MissionTextArea;
    private javax.swing.JLabel Missionlabel;
    private javax.swing.JScrollPane ScrollpaneMission;
    private javax.swing.JLabel aboutUsSlogan;
    private javax.swing.JLabel aboutustitle;
    private javax.swing.JLabel questionlabel;
    private javax.swing.JLabel titleaboutuspage;
    // End of variables declaration//GEN-END:variables
}
