/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Footwise.view;
import javax.swing.*;

/*
 * LMU ID: 23048665
 * Name: Devanshi Baishya
 */
public class Contactuspage extends javax.swing.JFrame {

    /**
     * Creates new form Contactuspage
     */
    public Contactuspage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogInSloganLabel = new javax.swing.JLabel();
        TitleHomelabel = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ContactUspagepanel = new javax.swing.JPanel();
        Logolabelcontactpage = new javax.swing.JLabel();
        ContactUsSlogan = new javax.swing.JLabel();
        titlecontactuspage = new javax.swing.JLabel();
        HomeButtonContact = new javax.swing.JButton();
        InformationButtonContact = new javax.swing.JButton();
        AboutUsButtonContact = new javax.swing.JButton();
        contactuslabel = new javax.swing.JLabel();
        Figurelabel = new javax.swing.JLabel();
        instagramlogolabel = new javax.swing.JLabel();
        Facebooklogolabel = new javax.swing.JLabel();
        whatsapplogolabel = new javax.swing.JLabel();
        facebooklabel = new javax.swing.JLabel();
        instagramlabel = new javax.swing.JLabel();
        whatsapplabel = new javax.swing.JLabel();
        Emaillogolabel = new javax.swing.JLabel();
        emaillabel = new javax.swing.JLabel();
        CallLogolabel = new javax.swing.JLabel();
        calllabel = new javax.swing.JLabel();
        footerlabel = new javax.swing.JLabel();

        LogInSloganLabel.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        LogInSloganLabel.setForeground(new java.awt.Color(255, 255, 255));
        LogInSloganLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogInSloganLabel.setText("Remember ... You Deserve the Best Or Nothing");

        TitleHomelabel.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        TitleHomelabel.setForeground(new java.awt.Color(255, 255, 255));
        TitleHomelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleHomelabel.setText("Foot~Wise");

        jButton4.setText("Blogs");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Footwise/resources/Facebook_icon.png"))); // NOI18N
        jLabel5.setText("FaceBook");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Foot~Wise");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ContactUspagepanel.setBackground(new java.awt.Color(51, 51, 0));
        ContactUspagepanel.setForeground(new java.awt.Color(255, 255, 255));

        Logolabelcontactpage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Footwise/resources/esmalllogo.png"))); // NOI18N

        ContactUsSlogan.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        ContactUsSlogan.setForeground(new java.awt.Color(255, 255, 255));
        ContactUsSlogan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ContactUsSlogan.setText("Remember ... You Deserve the Best Or Nothing");

        titlecontactuspage.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        titlecontactuspage.setForeground(new java.awt.Color(255, 255, 255));
        titlecontactuspage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlecontactuspage.setText("Foot~Wise");

        HomeButtonContact.setText("Home");

        InformationButtonContact.setText("Information ");
        InformationButtonContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformationButtonContactActionPerformed(evt);
            }
        });

        AboutUsButtonContact.setText("About ~ Us");
        AboutUsButtonContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsButtonContactActionPerformed(evt);
            }
        });

        contactuslabel.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        contactuslabel.setForeground(new java.awt.Color(204, 204, 255));
        contactuslabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contactuslabel.setText("Contact Us ");

        Figurelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Footwise/resources/ContactUs.jpg"))); // NOI18N

        instagramlogolabel.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        instagramlogolabel.setForeground(new java.awt.Color(204, 204, 255));
        instagramlogolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Footwise/resources/Instagram Icon.png"))); // NOI18N
        instagramlogolabel.setText("Instagram");

        Facebooklogolabel.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        Facebooklogolabel.setForeground(new java.awt.Color(204, 204, 255));
        Facebooklogolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Footwise/resources/Facebook_icon.png"))); // NOI18N
        Facebooklogolabel.setText("FaceBook");

        whatsapplogolabel.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        whatsapplogolabel.setForeground(new java.awt.Color(204, 204, 255));
        whatsapplogolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Footwise/resources/Whatsappicon.jpg"))); // NOI18N
        whatsapplogolabel.setText("Whatsapp");

        facebooklabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        facebooklabel.setForeground(new java.awt.Color(255, 204, 204));
        facebooklabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        facebooklabel.setText("Foot~Wise");

        instagramlabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        instagramlabel.setForeground(new java.awt.Color(255, 204, 204));
        instagramlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instagramlabel.setText("Foot~Wise");

        whatsapplabel.setBackground(new java.awt.Color(255, 204, 204));
        whatsapplabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        whatsapplabel.setForeground(new java.awt.Color(255, 204, 204));
        whatsapplabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        whatsapplabel.setText("+977 9766468677");

        Emaillogolabel.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        Emaillogolabel.setForeground(new java.awt.Color(204, 204, 255));
        Emaillogolabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Emaillogolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Footwise/resources/emailicon.jpg"))); // NOI18N
        Emaillogolabel.setText("Email Address");

        emaillabel.setForeground(new java.awt.Color(255, 204, 255));
        emaillabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emaillabel.setText("DR.group-foot~wise@gmail.com");

        CallLogolabel.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        CallLogolabel.setForeground(new java.awt.Color(204, 204, 255));
        CallLogolabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CallLogolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Footwise/resources/PhoneCallIcon.jpg"))); // NOI18N
        CallLogolabel.setText("Direct Call");

        calllabel.setBackground(new java.awt.Color(255, 204, 204));
        calllabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        calllabel.setForeground(new java.awt.Color(255, 204, 204));
        calllabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calllabel.setText("+977 9766468677");

        footerlabel.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        footerlabel.setForeground(new java.awt.Color(255, 255, 255));
        footerlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footerlabel.setText("Please Don't Forget To Join Us ");

        javax.swing.GroupLayout ContactUspagepanelLayout = new javax.swing.GroupLayout(ContactUspagepanel);
        ContactUspagepanel.setLayout(ContactUspagepanelLayout);
        ContactUspagepanelLayout.setHorizontalGroup(
            ContactUspagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactUspagepanelLayout.createSequentialGroup()
                .addComponent(Logolabelcontactpage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContactUspagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContactUspagepanelLayout.createSequentialGroup()
                        .addComponent(HomeButtonContact, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(InformationButtonContact, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AboutUsButtonContact, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(titlecontactuspage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ContactUsSlogan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(ContactUspagepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contactuslabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContactUspagepanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(ContactUspagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(facebooklabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Facebooklogolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instagramlogolabel)
                    .addComponent(instagramlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(whatsapplogolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(whatsapplabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(ContactUspagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContactUspagepanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(footerlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContactUspagepanelLayout.createSequentialGroup()
                        .addComponent(Figurelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addGroup(ContactUspagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Emaillogolabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emaillabel, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(CallLogolabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calllabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(29, 29, 29))
        );
        ContactUspagepanelLayout.setVerticalGroup(
            ContactUspagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactUspagepanelLayout.createSequentialGroup()
                .addGroup(ContactUspagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Logolabelcontactpage)
                    .addGroup(ContactUspagepanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titlecontactuspage, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ContactUsSlogan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContactUspagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomeButtonContact)
                    .addComponent(InformationButtonContact)
                    .addComponent(AboutUsButtonContact))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contactuslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ContactUspagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContactUspagepanelLayout.createSequentialGroup()
                        .addComponent(Facebooklogolabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(facebooklabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(instagramlogolabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(instagramlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(whatsapplogolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(whatsapplabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContactUspagepanelLayout.createSequentialGroup()
                        .addComponent(Emaillogolabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emaillabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CallLogolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calllabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContactUspagepanelLayout.createSequentialGroup()
                        .addComponent(Figurelabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(footerlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ContactUspagepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContactUspagepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       new Homepage().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void AboutUsButtonContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsButtonContactActionPerformed
        new About_Uspage().setVisible(true);
    }//GEN-LAST:event_AboutUsButtonContactActionPerformed

    private void InformationButtonContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformationButtonContactActionPerformed
       new Informationpage().setVisible(true);
    }//GEN-LAST:event_InformationButtonContactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contactuspage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contactuspage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contactuspage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contactuspage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contactuspage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUsButtonContact;
    private javax.swing.JLabel CallLogolabel;
    private javax.swing.JLabel ContactUsSlogan;
    private javax.swing.JPanel ContactUspagepanel;
    private javax.swing.JLabel Emaillogolabel;
    private javax.swing.JLabel Facebooklogolabel;
    private javax.swing.JLabel Figurelabel;
    private javax.swing.JButton HomeButtonContact;
    private javax.swing.JButton InformationButtonContact;
    private javax.swing.JLabel LogInSloganLabel;
    private javax.swing.JLabel Logolabelcontactpage;
    private javax.swing.JLabel TitleHomelabel;
    private javax.swing.JLabel calllabel;
    private javax.swing.JLabel contactuslabel;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JLabel facebooklabel;
    private javax.swing.JLabel footerlabel;
    private javax.swing.JLabel instagramlabel;
    private javax.swing.JLabel instagramlogolabel;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel titlecontactuspage;
    private javax.swing.JLabel whatsapplabel;
    private javax.swing.JLabel whatsapplogolabel;
    // End of variables declaration//GEN-END:variables
}
