/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Footwise.view;

import javax.swing.*;
import Footwise.controller.algorithms.ShoeBinarySearch;
import Footwise.controller.algorithms.selectionsort;
import Footwise.controller.algorithms.mergesort;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.Collections;

/*
 * LMU ID: 23048665
 * Name: Devanshi Baishya
 */
    public class Informationpage extends javax.swing.JFrame {
    private ArrayList<Shoe> ShoeList = new ArrayList<>();
    private DefaultTableModel tableModel;
    

    /**
     * Creates new form Informationpage
     */
    public Informationpage() {
        initComponents();
        tableModel = (DefaultTableModel) TableDetail.getModel();
        ShoeList = new ArrayList<>();
        
        addNewInitialShoe(new Shoe(103,"Nike Air Max 1 ", "Nike", "Yellow", 36, 23500));
        addNewInitialShoe(new Shoe(102,"Adidas UltraBoosr", "Adidas", "Black", 40, 30000));
        addNewInitialShoe(new Shoe(200,"Puma Suede", "Puma", "White", 26, 25000));
        addNewInitialShoe(new Shoe(125,"Converse Chuck Taylor", "Converse", "Blue", 30, 15000));
        addNewInitialShoe(new Shoe(251,"HOKA Clifton 9", "HOKA", "Brown", 36, 48000));
        addNewInitialShoe(new Shoe(180,"Oxford", "Bata", "Wine Red", 48,  26000));
        
        updateTable();
        
        SelectionSortButton.addActionListener(evt -> sortShoesByName());
        MergeSortButton.addActionListener(evt -> sortShoesBySerialNumber());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        MainpanelInformation = new javax.swing.JPanel();
        Logolabelcontactpage = new javax.swing.JLabel();
        InformationSlogan = new javax.swing.JLabel();
        titleinformationspage = new javax.swing.JLabel();
        homeinformation = new javax.swing.JButton();
        aboutusinformation = new javax.swing.JButton();
        contactinfo = new javax.swing.JButton();
        TableDataScrollPanel = new javax.swing.JScrollPane();
        TableDetail = new javax.swing.JTable();
        BinarySearchTextField = new javax.swing.JTextField();
        ShoeDataFormPanel = new javax.swing.JPanel();
        SerialNumberTextfield = new javax.swing.JTextField();
        ShoeNameTextField = new javax.swing.JTextField();
        BrandTextfield = new javax.swing.JTextField();
        ColorTextField = new javax.swing.JTextField();
        SizeTextField = new javax.swing.JTextField();
        PriceTextField = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();
        ReadButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        CreateButton = new javax.swing.JButton();
        SelectionSortButton = new javax.swing.JButton();
        MergeSortButton = new javax.swing.JButton();

        jTextField4.setBackground(new java.awt.Color(0, 102, 102));
        jTextField4.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Available Color", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sitka Text", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainpanelInformation.setBackground(new java.awt.Color(0, 51, 51));
        MainpanelInformation.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));

        Logolabelcontactpage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Footwise/resources/esmalllogo.png"))); // NOI18N

        InformationSlogan.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        InformationSlogan.setForeground(new java.awt.Color(255, 255, 255));
        InformationSlogan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InformationSlogan.setText("Remember ... You Deserve the Best Or Nothing");

        titleinformationspage.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        titleinformationspage.setForeground(new java.awt.Color(255, 255, 255));
        titleinformationspage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleinformationspage.setText("Foot~Wise");

        homeinformation.setText("Home");
        homeinformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeinformationActionPerformed(evt);
            }
        });

        aboutusinformation.setText("About Us");
        aboutusinformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutusinformationActionPerformed(evt);
            }
        });

        contactinfo.setText("Contact Us");
        contactinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactinfoActionPerformed(evt);
            }
        });

        TableDetail.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 0, 0)));
        TableDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "S.N", "Shoe Name", "Brand", "Color", "Size", "Price"
            }
        ));
        TableDataScrollPanel.setViewportView(TableDetail);

        BinarySearchTextField.setBackground(new java.awt.Color(0, 102, 102));
        BinarySearchTextField.setForeground(new java.awt.Color(255, 255, 255));
        BinarySearchTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BinarySearchTextField.setAutoscrolls(false);
        BinarySearchTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 2, true), "Search Here: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Stencil", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        javax.swing.GroupLayout MainpanelInformationLayout = new javax.swing.GroupLayout(MainpanelInformation);
        MainpanelInformation.setLayout(MainpanelInformationLayout);
        MainpanelInformationLayout.setHorizontalGroup(
            MainpanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainpanelInformationLayout.createSequentialGroup()
                .addComponent(Logolabelcontactpage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainpanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainpanelInformationLayout.createSequentialGroup()
                        .addComponent(titleinformationspage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addComponent(InformationSlogan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1356, Short.MAX_VALUE)
                    .addGroup(MainpanelInformationLayout.createSequentialGroup()
                        .addComponent(homeinformation)
                        .addGap(18, 18, 18)
                        .addComponent(aboutusinformation)
                        .addGap(18, 18, 18)
                        .addComponent(contactinfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BinarySearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))))
            .addGroup(MainpanelInformationLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(TableDataScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1044, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainpanelInformationLayout.setVerticalGroup(
            MainpanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainpanelInformationLayout.createSequentialGroup()
                .addGroup(MainpanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainpanelInformationLayout.createSequentialGroup()
                        .addComponent(titleinformationspage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InformationSlogan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Logolabelcontactpage))
                .addGap(18, 18, 18)
                .addGroup(MainpanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactinfo)
                    .addComponent(aboutusinformation)
                    .addComponent(homeinformation)
                    .addComponent(BinarySearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(TableDataScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        ShoeDataFormPanel.setBackground(new java.awt.Color(51, 51, 0));
        ShoeDataFormPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 255, 255), new java.awt.Color(204, 255, 255))));
        ShoeDataFormPanel.setForeground(new java.awt.Color(255, 255, 255));

        SerialNumberTextfield.setBackground(new java.awt.Color(204, 255, 204));
        SerialNumberTextfield.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Serial Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Stencil", 0, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        ShoeNameTextField.setBackground(new java.awt.Color(204, 255, 204));
        ShoeNameTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Shoe Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Stencil", 0, 14), new java.awt.Color(0, 102, 102))); // NOI18N
        ShoeNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShoeNameTextFieldActionPerformed(evt);
            }
        });

        BrandTextfield.setBackground(new java.awt.Color(204, 255, 204));
        BrandTextfield.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Brand", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Stencil", 0, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        ColorTextField.setBackground(new java.awt.Color(204, 255, 204));
        ColorTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Color", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Stencil", 0, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        SizeTextField.setBackground(new java.awt.Color(204, 255, 204));
        SizeTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Size", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Stencil", 0, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        PriceTextField.setBackground(new java.awt.Color(204, 255, 204));
        PriceTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Price", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Stencil", 0, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        UpdateButton.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(102, 102, 0));
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        ReadButton.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        ReadButton.setForeground(new java.awt.Color(102, 102, 0));
        ReadButton.setText("Read");
        ReadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadButtonActionPerformed(evt);
            }
        });

        DeleteButton.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(102, 102, 0));
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        CreateButton.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        CreateButton.setForeground(new java.awt.Color(51, 51, 0));
        CreateButton.setText("CREATE");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        SelectionSortButton.setText("Selection By Shoe Name");

        MergeSortButton.setText("Selection By Serial Number");

        javax.swing.GroupLayout ShoeDataFormPanelLayout = new javax.swing.GroupLayout(ShoeDataFormPanel);
        ShoeDataFormPanel.setLayout(ShoeDataFormPanelLayout);
        ShoeDataFormPanelLayout.setHorizontalGroup(
            ShoeDataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShoeDataFormPanelLayout.createSequentialGroup()
                .addGroup(ShoeDataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ShoeDataFormPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ShoeDataFormPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(ShoeDataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ShoeNameTextField)
                            .addComponent(SerialNumberTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(ShoeDataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ColorTextField)
                            .addComponent(BrandTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(ShoeDataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ShoeDataFormPanelLayout.createSequentialGroup()
                                .addComponent(PriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ShoeDataFormPanelLayout.createSequentialGroup()
                                .addComponent(SizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(ShoeDataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(MergeSortButton, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(SelectionSortButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(197, 197, 197)
                                .addGroup(ShoeDataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UpdateButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ReadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        ShoeDataFormPanelLayout.setVerticalGroup(
            ShoeDataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShoeDataFormPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(CreateButton)
                .addGroup(ShoeDataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ShoeDataFormPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ShoeDataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SerialNumberTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BrandTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReadButton))
                        .addGroup(ShoeDataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ShoeDataFormPanelLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(ShoeDataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ShoeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ShoeDataFormPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UpdateButton)
                                .addGap(18, 18, 18)
                                .addComponent(DeleteButton))))
                    .addGroup(ShoeDataFormPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(SelectionSortButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(MergeSortButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainpanelInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ShoeDataFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainpanelInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShoeDataFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void homeinformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeinformationActionPerformed
        new Homepage().setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_homeinformationActionPerformed

    private void contactinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactinfoActionPerformed
        new Contactuspage().setVisible(true);
    }//GEN-LAST:event_contactinfoActionPerformed

    private void aboutusinformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutusinformationActionPerformed
         new About_Uspage().setVisible(true);
    }//GEN-LAST:event_aboutusinformationActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void ShoeNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShoeNameTextFieldActionPerformed

    }//GEN-LAST:event_ShoeNameTextFieldActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
                int selectedRow = TableDetail.getSelectedRow();
        if (selectedRow != -1) {
           try {
                int serialNumber = Integer.parseInt(SerialNumberTextfield.getText());
                String name = ShoeNameTextField.getText();
                String brand = BrandTextfield.getText();
                String color = ColorTextField.getText();
                int size = Integer.parseInt(SizeTextField.getText());
                int price = Integer.parseInt(PriceTextField.getText());
                                
                ShoeList.set(selectedRow, new Shoe(serialNumber, name, brand, color, size, price));
                updateTable();
                clearFields();
           }  catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please enter valid integer values for Serial Number, Size, and Price.");
           }
           } else {
            JOptionPane.showMessageDialog(this, "Select a shoe to update.");
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void ReadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadButtonActionPerformed
            int selectedRow = TableDetail.getSelectedRow();
            if (selectedRow != -1) {
                Shoe selectedShoe = ShoeList.get(selectedRow);
                String message = "Shoe Details:\n" +
                         "Serial Number: " + selectedShoe.getSerialNumber() + "\n" +
                         "Name: " + selectedShoe.getName() + "\n" +
                         "Brand: " + selectedShoe.getBrand() + "\n" +
                         "Color: " + selectedShoe.getColor() + "\n" +
                         "Size: " + selectedShoe.getSize() + "\n" +
                         "Price: " + selectedShoe.getPrice();
        JOptionPane.showMessageDialog(this, message, "Shoe Information", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Select a shoe to read.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_ReadButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
                int selectedRow = TableDetail.getSelectedRow();
        if (selectedRow != -1) {
            ShoeList.remove(selectedRow);
            updateTable();
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, "Select a shoe to delete.");
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
            try {
                int serialNumber = Integer.parseInt(SerialNumberTextfield.getText());
                String name = ShoeNameTextField.getText();
                String brand = BrandTextfield.getText();
                String color = ColorTextField.getText();
                int size = Integer.parseInt(SizeTextField.getText());
                int price = Integer.parseInt(PriceTextField.getText());


        Shoe newShoe = new Shoe(serialNumber, name, brand, color, size, price);
        
        ShoeList.add(newShoe);
        updateTable();
        clearFields();
            } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid integer values for Serial Number, Size, and Price.");
        }
    }//GEN-LAST:event_CreateButtonActionPerformed

        private void updateTable() {
        tableModel.setRowCount(0); // Clear existing rows
        for (Shoe shoe : ShoeList) {
            tableModel.addRow(new Object[]{
                shoe.getSerialNumber(),
                shoe.getName(),
                shoe.getBrand(),
                shoe.getColor(),
                shoe.getSize(),
                shoe.getPrice()
            });
        }
        int rowsToAdd = 5 - ShoeList.size();
        for (int i = 0; i < rowsToAdd; i++) {
            tableModel.addRow(new Object[]{null, null, null, null, null, null});
    }
        
            BinarySearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binarySearchShoeName();
            }
               });
    }
         private void sortShoesByName() {
        selectionsort selectionSort = new selectionsort();
        // Sort the ShoeList by name in ascending order
        ShoeList = new ArrayList<>(selectionSort.sortByShoeName(ShoeList, false));
        updateTable(); // Update the table with the sorted list
    }
        private void sortShoesBySerialNumber() {
        mergesort mergeSort = new mergesort();
        // Sort the ShoeList by serial number in ascending order
        ShoeList = new ArrayList<>(mergeSort.sortBySerialNumber(ShoeList, false));
        updateTable(); 
    } 
         
        private void binarySearchShoeName() {
            String searchTerm = BinarySearchTextField.getText();
            ShoeBinarySearch binarySearch = new ShoeBinarySearch();
        // Sort the ShoeList by name for binary search
        Collections.sort(ShoeList, (s1, s2) -> s1.getName().compareToIgnoreCase(s2.getName()));
           System.out.println("Searching for: " + searchTerm);
    System.out.println("Shoe List:");
    for (Shoe shoe : ShoeList) {
        System.out.println(shoe.getName());
    }
        
        Shoe foundShoe = binarySearch.searchByName(searchTerm, ShoeList, 0, ShoeList.size() - 1);

        // Show message based on search result
        if (foundShoe != null) {
            JOptionPane.showMessageDialog(this, "Shoe found: " + foundShoe.getName());
        } else {
            JOptionPane.showMessageDialog(this, "Shoe not found: " + searchTerm);
        }
    }
        
        
        private void addNewInitialShoe(Shoe Shoe) {
            ShoeList.add(Shoe);
        }

    private void clearFields() {
        SerialNumberTextfield.setText("");
        ShoeNameTextField.setText("");
        BrandTextfield.setText("");
        ColorTextField.setText("");
        SizeTextField.setText("");
        PriceTextField.setText("");
    }
    
    public class Shoe {
        private int serialNumber;
        private String name;
        private String brand;
        private String color;
        private int size;
        private int price;
        
        public Shoe(int serialNumber, String name, String brand, String color, int size, int price) {
            this.serialNumber = serialNumber;
            this.name = name;
            this.brand = brand;
            this.color = color;
            this.size = size;
            this.price = price;
        }
            
        public int getSerialNumber() { return serialNumber; }
        public String getName() { return name; }
        public String getBrand() { return brand; }
        public String getColor() { return color; }
        public int getSize() { return size; }
        public int getPrice() { return price; }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informationpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BinarySearchTextField;
    private javax.swing.JTextField BrandTextfield;
    private javax.swing.JTextField ColorTextField;
    private javax.swing.JButton CreateButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel InformationSlogan;
    private javax.swing.JLabel Logolabelcontactpage;
    private javax.swing.JPanel MainpanelInformation;
    private javax.swing.JButton MergeSortButton;
    private javax.swing.JTextField PriceTextField;
    private javax.swing.JButton ReadButton;
    private javax.swing.JButton SelectionSortButton;
    private javax.swing.JTextField SerialNumberTextfield;
    private javax.swing.JPanel ShoeDataFormPanel;
    private javax.swing.JTextField ShoeNameTextField;
    private javax.swing.JTextField SizeTextField;
    private javax.swing.JScrollPane TableDataScrollPanel;
    private javax.swing.JTable TableDetail;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton aboutusinformation;
    private javax.swing.JButton contactinfo;
    private javax.swing.JButton homeinformation;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel titleinformationspage;
    // End of variables declaration//GEN-END:variables
}
