/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Footwise.view;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * LMU ID: 23048665
 * Name: Devanshi Baishya
 */
public class loadingpage extends javax.swing.JFrame {
    
    private Timer timer;
    private int progressValue = 0;
    
    /**
     * Creating new form loading page
     */
    public loadingpage() {
        initComponents();
        startLoading();
    }

    private void startLoading() {
        timer = new Timer(100, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                                progressValue += 5; // Increment progress
                progressbarloading.setValue(progressValue);

                // Checking loading is complete 
                if (progressValue >= 100) {
                    timer.stop(); // For Stop the timer
                    openloginpage(); // It'Open the login page
            }
            }
        });
        timer.start();
    }
    
    private void openloginpage() {
        this.dispose();
        new loginpage().setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainLoadingpanel = new javax.swing.JPanel();
        ShoeLabelFigure = new javax.swing.JLabel();
        logolabel = new javax.swing.JLabel();
        Headingloading = new javax.swing.JLabel();
        LoadingSlogan = new javax.swing.JLabel();
        progressbarloading = new javax.swing.JProgressBar();
        loginlooadingmsglabel = new javax.swing.JLabel();
        OneMomentLabelloading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainLoadingpanel.setBackground(new java.awt.Color(0, 51, 51));

        ShoeLabelFigure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Footwise/resources/shoeloading2.jpg"))); // NOI18N

        logolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Footwise/resources/esmalllogo.png"))); // NOI18N

        Headingloading.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        Headingloading.setForeground(new java.awt.Color(204, 255, 255));
        Headingloading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Headingloading.setText("Foot~Wise ");

        LoadingSlogan.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        LoadingSlogan.setForeground(new java.awt.Color(255, 255, 255));
        LoadingSlogan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoadingSlogan.setText("Remember ... You Deserve the Best Or Nothing");

        loginlooadingmsglabel.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        loginlooadingmsglabel.setForeground(new java.awt.Color(153, 153, 153));
        loginlooadingmsglabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginlooadingmsglabel.setText("Loading To Login Page ");

        OneMomentLabelloading.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        OneMomentLabelloading.setForeground(new java.awt.Color(153, 153, 153));
        OneMomentLabelloading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OneMomentLabelloading.setText("One Moment Please ");

        javax.swing.GroupLayout MainLoadingpanelLayout = new javax.swing.GroupLayout(MainLoadingpanel);
        MainLoadingpanel.setLayout(MainLoadingpanelLayout);
        MainLoadingpanelLayout.setHorizontalGroup(
            MainLoadingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLoadingpanelLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(ShoeLabelFigure)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addGroup(MainLoadingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(progressbarloading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginlooadingmsglabel, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(OneMomentLabelloading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58))
            .addGroup(MainLoadingpanelLayout.createSequentialGroup()
                .addComponent(logolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainLoadingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Headingloading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LoadingSlogan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        MainLoadingpanelLayout.setVerticalGroup(
            MainLoadingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLoadingpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainLoadingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainLoadingpanelLayout.createSequentialGroup()
                        .addComponent(Headingloading, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LoadingSlogan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(MainLoadingpanelLayout.createSequentialGroup()
                        .addComponent(logolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)))
                .addGroup(MainLoadingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainLoadingpanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(loginlooadingmsglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(progressbarloading, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(OneMomentLabelloading))
                    .addGroup(MainLoadingpanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ShoeLabelFigure)))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainLoadingpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainLoadingpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loadingpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loadingpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loadingpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loadingpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Creating and displaying the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loadingpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Headingloading;
    private javax.swing.JLabel LoadingSlogan;
    private javax.swing.JPanel MainLoadingpanel;
    private javax.swing.JLabel OneMomentLabelloading;
    private javax.swing.JLabel ShoeLabelFigure;
    private javax.swing.JLabel loginlooadingmsglabel;
    private javax.swing.JLabel logolabel;
    private javax.swing.JProgressBar progressbarloading;
    // End of variables declaration//GEN-END:variables
}
