/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Footwise.view;
import javax.swing.*;

 /*
 * LMU ID: 23048665
 * Name: Devanshi Baishya
 */
public class loginpage extends javax.swing.JFrame {
        private static final String MY_NAME = "devanshi";
        private static final String MY_EMAIL = "devanshi@gmail.com";
        private static final String MY_PASSWORD = "devanshi123";

    /**
     * Creates new form loginpage
     */
    public loginpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        BigLogolabel = new javax.swing.JLabel();
        LogInPanel2 = new javax.swing.JPanel();
        HeaderLabel = new javax.swing.JLabel();
        LogInSloganLabel = new javax.swing.JLabel();
        SiginLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        Namelabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        PasswordFieldLogin = new javax.swing.JPasswordField();
        EmailTextFieldLogin = new javax.swing.JTextField();
        NameTextFieldLogin = new javax.swing.JTextField();
        LoginButtonLogin = new javax.swing.JButton();
        ForgetPasswordButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(130, 139, 80));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        BigLogolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Footwise/resources/Untitled_design-removebg-preview.png"))); // NOI18N

        LogInPanel2.setBackground(new java.awt.Color(51, 51, 0));

        HeaderLabel.setBackground(new java.awt.Color(0, 0, 0));
        HeaderLabel.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        HeaderLabel.setForeground(new java.awt.Color(255, 255, 255));
        HeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeaderLabel.setText("WelCome You To Foot~Wise");

        LogInSloganLabel.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        LogInSloganLabel.setForeground(new java.awt.Color(255, 255, 255));
        LogInSloganLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogInSloganLabel.setText("Remember ... You Deserve the Best Or Nothing");

        SiginLabel.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        SiginLabel.setForeground(new java.awt.Color(255, 255, 255));
        SiginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SiginLabel.setText("Let's Sign In The Page ");

        PasswordLabel.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordLabel.setText("Password:");
        PasswordLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        Namelabel.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        Namelabel.setForeground(new java.awt.Color(255, 255, 255));
        Namelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Namelabel.setText("Full Name :");
        Namelabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(255, 255, 255), java.awt.Color.white, java.awt.Color.white));

        EmailLabel.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmailLabel.setText("Email Address:");
        EmailLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        PasswordFieldLogin.setBackground(new java.awt.Color(51, 51, 0));
        PasswordFieldLogin.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        PasswordFieldLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordFieldLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, new java.awt.Color(204, 204, 255), java.awt.Color.gray, java.awt.Color.gray));
        PasswordFieldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldLoginActionPerformed(evt);
            }
        });

        EmailTextFieldLogin.setBackground(new java.awt.Color(51, 51, 0));
        EmailTextFieldLogin.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        EmailTextFieldLogin.setForeground(new java.awt.Color(255, 255, 255));
        EmailTextFieldLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EmailTextFieldLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));

        NameTextFieldLogin.setBackground(new java.awt.Color(51, 51, 0));
        NameTextFieldLogin.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        NameTextFieldLogin.setForeground(new java.awt.Color(255, 255, 255));
        NameTextFieldLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NameTextFieldLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));

        LoginButtonLogin.setBackground(new java.awt.Color(51, 51, 0));
        LoginButtonLogin.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        LoginButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        LoginButtonLogin.setText("Log~In");
        LoginButtonLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        LoginButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonLoginActionPerformed(evt);
            }
        });

        ForgetPasswordButton.setBackground(new java.awt.Color(51, 51, 0));
        ForgetPasswordButton.setForeground(new java.awt.Color(255, 255, 255));
        ForgetPasswordButton.setText("Forget My Password");
        ForgetPasswordButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        ForgetPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgetPasswordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LogInPanel2Layout = new javax.swing.GroupLayout(LogInPanel2);
        LogInPanel2.setLayout(LogInPanel2Layout);
        LogInPanel2Layout.setHorizontalGroup(
            LogInPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LogInPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogInSloganLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE))
            .addComponent(SiginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LogInPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(LogInPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LogInPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PasswordFieldLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(EmailTextFieldLogin)
                    .addComponent(NameTextFieldLogin))
                .addGap(76, 76, 76))
            .addGroup(LogInPanel2Layout.createSequentialGroup()
                .addGroup(LogInPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogInPanel2Layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(LoginButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LogInPanel2Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(ForgetPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LogInPanel2Layout.setVerticalGroup(
            LogInPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogInSloganLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SiginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(LogInPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Namelabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(NameTextFieldLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LogInPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EmailTextFieldLogin)
                    .addComponent(EmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LogInPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoginButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ForgetPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BigLogolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogInPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(BigLogolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(LogInPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordFieldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldLoginActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldLoginActionPerformed

    private void LoginButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonLoginActionPerformed
        String name = NameTextFieldLogin.getText();
        String email = EmailTextFieldLogin.getText();
        String password = new String(PasswordFieldLogin.getPassword());
        
        if (name.equals(MY_NAME) && email.equals(MY_EMAIL) && password.equals(MY_PASSWORD)) {
            new Homepage().setVisible(true);
            this.dispose(); // Close the login page
        } else {
            JOptionPane.showMessageDialog(this, "Invalid credentials. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LoginButtonLoginActionPerformed

    private void ForgetPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgetPasswordButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Password recovery feature is not implemented yet.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ForgetPasswordButtonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BigLogolabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTextFieldLogin;
    private javax.swing.JButton ForgetPasswordButton;
    private javax.swing.JLabel HeaderLabel;
    private javax.swing.JPanel LogInPanel2;
    private javax.swing.JLabel LogInSloganLabel;
    private javax.swing.JButton LoginButtonLogin;
    private javax.swing.JTextField NameTextFieldLogin;
    private javax.swing.JLabel Namelabel;
    private javax.swing.JPasswordField PasswordFieldLogin;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel SiginLabel;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
